version: '3.8'
services:
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    network_mode: "host"
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=${ID}
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9092
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.51:2181,192.168.1.52:2181,192.168.1.53:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - JMX_PORT=9999
      - 'KAFKA_HEAP_OPTS=-Xmx1g -Xms1g'      
      - TZ=Asia/Shanghai
    depends_on:
      - zoo
    volumes:
      - /etc/hosts:/etc/hosts
      - ${OPS_ROOT}/service/mq/kafka/data:/kafka/kafka-logs-localhost.localdomain
      - ${OPS_ROOT}/service/mq/kafka/logs:/opt/kafka/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure   