version: '3.6'
services:

  openresty:
    image: openresty/openresty:centos
    restart: always
    container_name: resty
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
#      - ./resty:/usr/local/openresty/lualib/resty     #!--$  docker cp resty:/usr/local/openresty/lualib/resty .
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf:/etc/nginx 
      - ./logs:/usr/local/openresty/nginx/logs  
      - /data/static:/usr/local/openresty/nginx/html #nginx static dir
      - ./data/.cache:/data/.cache                   #nginx cache dir
#      - ./apisix:/usr/local/apisix #apisix log, if not use apisix, comment[volumes<apisix,script>,command]
#      - ./script:/usr/local/script
#    command:
#      - sh
#      - -c 
#      - |
#          chmod +x /usr/local/script/*.sh
#          /usr/local/script/startup.sh            
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure
