version: "3.6"
services:
  java:
    image: openjdk:11-oraclelinux7
    restart: on-failure:5
    container_name: java
    user: dev:dev #1001<uid>:1001<gid>  cat /etc/passwd
    environment:
      TZ: Asia/Shanghai
    network_mode: "host"
    volumes:
      - /data/dflc:/data/dflc
    command:
      - sh
      - -c
      - |
        chmod +x /data/dflc/start.sh
        /data/dflc/start.sh

# cat >/etc/apt/sources.list <<EOF
# deb http://deb.debian.org/debian buster main
# deb http://security.debian.org/debian-security buster/updates main
# deb http://deb.debian.org/debian buster-updates main
# EOF
#apt-get update  # if error exec apt-get upgrade
#apt-get install -y procps
#dpkg-reconfigure dash

# echo "deb http://mirrors.aliyun.com/debian/ jessie main non-free contrib" > /etc/apt/sources.list \
#   && echo "deb http://mirrors.aliyun.com/debian/ jessie-updates main non-free contrib" >> /etc/apt/sources.list \
#   && echo "deb http://mirrors.aliyun.com/debian-security/ jessie/updates main non-free contrib" >> /etc/apt/sources.list

# mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
# echo 'deb http://mirrors.163.com/debian/ jessie main non-free contrib' > /etc/apt/sources.list && \
# echo 'deb http://mirrors.163.com/debian/ jessie-updates main non-free contrib' >> /etc/apt/sources.list && \
# echo 'deb http://mirrors.163.com/debian-security/ jessie/updates main non-free contrib' >> /etc/apt/sources.list
