version: '3.8'
services:
  frps:
    image: snowdreamtech/frps
    network_mode: "host"
    container_name: frps
    restart: always    
    volumes:
      - /etc/hosts:/etc/hosts
      - ./frps.ini:/etc/frp/frps.ini
