version: '3.6'
services:

  v2ray:
    image: v2fly/v2fly-core
    restart: always
    container_name: v2ray
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
       - ./conf:/etc/v2ray