version: "3.7"
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    ports:
      - 1080:1080
      - 1081:1081
    command: v2ray --config=/etc/v2ray/config.json
    volumes:
      - ./conf:/etc/v2ray
    restart: unless-stopped