version: "3"

services:
  vm_dev:
    image: opmatrix/sshd-docker-builder
    container_name: vm_dev
    restart: on-failure:5
    user: #<user or uid>:<group or gid>
    privileged: true
    mem_limit: 4g
    mem_reservation: 512m
    cpus: 2
    ports:
      - "2222:22"
      - "5906-5909:5906-5909"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${OPS_ROOT}/script:/data/script
      - ${OPS_ROOT}/service/sdk/:/data/service/sdk/
      - ${OPS_ROOT}/workspace/:/data/workspace/
      - ./commons:/data/service/commons
      - ./dev:/data
    command:
      - sh
      - -c
      - |
        chmod +x /data/dflc/start.sh
        /data/dflc/start.sh
